import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "../globals.css"
import { cn } from "@/lib/utils"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en' className='custom-min-h-screen w-screen'>
			<body
				className={cn(
					"custom-min-h-screen max-width-wrapper relative font-sans antialiased bg-stone-950 text-stone-200",
					inter.className
				)}
			>
				<main className='custom-min-h-screen'>{children}</main>
			</body>
		</html>
	)
}
